<template>
    <div class="dashboard-container">
      <!-- Sidebar -->
      <div class="sidebar">
        <div class="logo-container pa-4">
          <div class="d-flex align-center">
            <v-img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/vuejs/vuejs-original.svg" max-width="40" class="logo" />
            <div class="ml-2 text-h6 font-weight-bold text-black">CODE<span class="text-green">NICELY</span></div>
          </div>
        </div>
        
        <v-list>
          <v-list-item prepend-icon="mdi-account-group" title="Team" class="sidebar-item"></v-list-item>
          <v-list-item prepend-icon="mdi-file-document" title="Invoice" class="sidebar-item active"></v-list-item>
        </v-list>
        
        <div class="logout-container">
          <v-btn variant="outlined" color="error" block class="logout-btn" @click="confirmLogout">
            Logout
          </v-btn>
        </div>
      </div>
      
      <!-- Main Content -->
      <div class="main-content">
        <div class="header d-flex justify-space-between align-center px-4 py-2">
          <h1 class="text-h5 text-black">Invoice List</h1>
          <v-text-field
            v-model="search"
            prepend-inner-icon="mdi-magnify"
            placeholder="Search"
            variant="outlined"
            density="compact"
            hide-details
            class="search-field"
            style="max-width: 300px; background-color: white; color: black;"
          ></v-text-field>
        </div>
        
        <div class="content-area pa-4">
          <div class="d-flex justify-space-between mb-4">
            <v-select
              v-model="filter"
              :items="['All', 'USER', 'PANEL']"
              label="Filter by Generated By"
              variant="outlined"
              dense
              style="max-width: 200px; background-color: white; color: black;"
            ></v-select>
            <v-btn color="primary" @click="$router.push('/create-invoice')">Create Invoice</v-btn>
          </div>
          
          <v-tabs class="mb-4">
            <v-tab>Total</v-tab>
            <v-tab>User Generated</v-tab>
            <v-tab>Panel Generated</v-tab>
          </v-tabs>
          
          <div class="stats-container d-flex mb-6">
            <v-card class="stats-card mr-4" color="#1976D2" dark>
              <v-card-text>
                <div class="text-h4 font-weight-bold">{{ totalInvoices }}</div>
                <div class="text-subtitle-1">Total</div>
              </v-card-text>
            </v-card>
            
            <v-card class="stats-card mr-4" color="#42A5F5" dark>
              <v-card-text>
                <div class="text-h4 font-weight-bold">{{ totalUserGenerated }}</div>
                <div class="text-subtitle-1">User Generated</div>
              </v-card-text>
            </v-card>
            
            <v-card class="stats-card" color="#64B5F6" dark>
              <v-card-text>
                <div class="text-h4 font-weight-bold">{{ totalPanelGenerated }}</div>
                <div class="text-subtitle-1">Panel Generated</div>
              </v-card-text>
            </v-card>
          </div>
  
          <!-- Invoice Table -->
          <v-table>
            <thead>
              <tr>
                <th class="text-left">Invoice ID</th>
                <th class="text-left">Initiated On</th>
                <th class="text-left">Generated By</th>
                <th class="text-left">Customer Name</th>
                <th class="text-left">Action</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="invoice in filteredInvoices" :key="invoice.id">
                <td>{{ invoice.displayId }}</td>
                <td>{{ invoice.initiatedOn }}</td>
                <td>{{ invoice.generatedBy }}</td>
                <td>{{ invoice.customerName }}</td>
                <td>
                  <v-btn color="primary" variant="outlined" @click="editInvoice(invoice.id)">Edit</v-btn>
                </td>
              </tr>
            </tbody>
          </v-table>
        </div>
      </div>
  
      <!-- Logout Confirmation Dialog -->
      <v-dialog v-model="logoutDialog" max-width="400">
        <v-card>
          <v-card-title>Confirm Logout</v-card-title>
          <v-card-text>Are you sure you want to logout?</v-card-text>
          <v-card-actions>
            <v-spacer></v-spacer>
            <v-btn color="red" @click="logout">Yes</v-btn>
            <v-btn @click="logoutDialog = false">No</v-btn>
          </v-card-actions>
        </v-card>
      </v-dialog>
    </div>
  </template>
  
<script>
  import axios from 'axios'
  export default {
    data() {
      return {
        search: "",
        filter: "All",
        totalInvoices: 0,
        totalUserGenerated: 0,
        totalPanelGenerated: 0,
        logoutDialog: false,
        invoices: []
      };
    },
    computed: {
      filteredInvoices() {
        return this.invoices.filter(invoice => {
          return (
            (this.filter === 'All' || invoice.generatedBy === this.filter.replace(' Generated', '')) &&
            (invoice.customerName.toLowerCase().includes(this.search.toLowerCase()) || invoice.id.includes(this.search))
          );
        });
      }
    },
    methods: {
      async fetchInvoices() {
        try {
          const response = await axios.get("https://invoices-codenicely-be.onrender.com/api/invoices/all");
          this.invoices = this.parseInvoices(response.data.allInvoices)
          this.totalInvoices = this.invoices.length
          this.totalUserGenerated = this.invoices.filter(invoice => invoice.generatedBy === "USER").length;
          this.totalPanelGenerated = this.totalInvoices - this.totalUserGenerated
        } catch (error) {
          console.error("Error fetching invoices:", error);
        }
      },
      editInvoice(id) {
        console.log('Editing invoice:', id);
      },
      confirmLogout() {
        this.logoutDialog = true;
      },
      logout() {
        this.logoutDialog = false;
        this.$router.push('/');
      },
      parseInvoices(invoices) {
        if(invoices.length === 0) {
          return [];
        }
        return invoices?.map((invoice, index) => ({
          id: invoice._id,
          displayId: `INV${(invoice._id + 1).substr(-4)}`, // Sequential ID
          initiatedOn: new Date(invoice.invoiceToDetails.paymentDate).toISOString().split("T")[0], // Convert date
          generatedBy: invoice.createdBy, // USER or PANEL
          customerName: invoice.invoiceToDetails.name // Extract customer name
        }))
      }
    },
    mounted() {
      this.fetchInvoices(); // Fetch data when component is mounted
    }
  };
  </script>
  
  <style scoped>
  .dashboard-container {
    display: flex;
    height: 100vh;
    background-color: #f0f0f0;
  }
  
  .sidebar {
    width: 250px;
    background-color: #ffffff;
    border-right: 1px solid #e0e0e0;
    display: flex;
    flex-direction: column;
    height: 100%;
  }
  
  .sidebar-item {
    border-radius: 0;
  }
  
  .sidebar-item.active {
    background-color: #1976D2;
    color: white;
  }
  
  .logout-container {
    margin-top: auto;
    padding: 16px;
  }
  
  .main-content {
    flex: 1;
    display: flex;
    flex-direction: column;
    background-color: #ffffff;
  }
  
  .header {
    background-color: #f5f5f5;
    border-bottom: 1px solid #e0e0e0;
  }
  
  .content-area {
    flex: 1;
    overflow-y: auto;
    background-color: #ffffff;
  }
  
  .stats-container {
    gap: 16px;
    display: flex;
    justify-content: space-between;
  }
  
  .stats-card {
    flex: 1;
    text-align: center;
    padding: 16px;
    border-radius: 8px;
    box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1);
  }
  </style>
  